import "./globals.css";
import { Inter } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "./component/layout/Navbar";
import Footer from "./component/layout/Footer";
import Head from "next/head";
const plus_Jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <Head>
          <link rel="icon" href="/favicon.png" />
        </Head>
        <body>
          <Navbar />
          {children}
          <Footer />
        
        </body>
      </html>
    
  );
}
